//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogOn.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isEnter", ReplyAction="http://tempuri.org/IService1/isEnterResponse")]
        bool isEnter(LogOn.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isEnter", ReplyAction="http://tempuri.org/IService1/isEnterResponse")]
        System.Threading.Tasks.Task<bool> isEnterAsync(LogOn.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Reg", ReplyAction="http://tempuri.org/IService1/RegResponse")]
        string Reg(LogOn.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Reg", ReplyAction="http://tempuri.org/IService1/RegResponse")]
        System.Threading.Tasks.Task<string> RegAsync(LogOn.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveFile", ReplyAction="http://tempuri.org/IService1/SaveFileResponse")]
        void SaveFile(byte[] bytes, string ext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveFile", ReplyAction="http://tempuri.org/IService1/SaveFileResponse")]
        System.Threading.Tasks.Task SaveFileAsync(byte[] bytes, string ext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveToFile", ReplyAction="http://tempuri.org/IService1/SaveToFileResponse")]
        void SaveToFile(string ext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveToFile", ReplyAction="http://tempuri.org/IService1/SaveToFileResponse")]
        System.Threading.Tasks.Task SaveToFileAsync(string ext);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : LogOn.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<LogOn.ServiceReference1.IService1>, LogOn.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool isEnter(LogOn.ServiceReference1.User user) {
            return base.Channel.isEnter(user);
        }
        
        public System.Threading.Tasks.Task<bool> isEnterAsync(LogOn.ServiceReference1.User user) {
            return base.Channel.isEnterAsync(user);
        }
        
        public string Reg(LogOn.ServiceReference1.User user) {
            return base.Channel.Reg(user);
        }
        
        public System.Threading.Tasks.Task<string> RegAsync(LogOn.ServiceReference1.User user) {
            return base.Channel.RegAsync(user);
        }
        
        public void SaveFile(byte[] bytes, string ext) {
            base.Channel.SaveFile(bytes, ext);
        }
        
        public System.Threading.Tasks.Task SaveFileAsync(byte[] bytes, string ext) {
            return base.Channel.SaveFileAsync(bytes, ext);
        }
        
        public void SaveToFile(string ext) {
            base.Channel.SaveToFile(ext);
        }
        
        public System.Threading.Tasks.Task SaveToFileAsync(string ext) {
            return base.Channel.SaveToFileAsync(ext);
        }
    }
}
